### ISSUE TITLE
Widget not updating

### ISSUE THREAD

**Issue by joshatron** [hwshim0810/DailyCommit-Android-Kotlin#2]
Hey, I like your app a lot. I have a problem though. I tried to use the widget, but it seems stuck on the first day I installed the app and never updates. I am running 8.1.0 on a Pixel XL. Let me know if you need any more information.

**Comment by hwshim0810** [comment]
First of all appreciate that using this app.
Thanks for the issue. I will check after and write more comment.😆

The automatic or manual or both updates did not work?
it will help fix them.

**Comment by joshatron** [comment]
I am not sure how to trigger the manual update. If you let me know I can try it. The only way I seem to be able to update it is clearing the cache of the app.

**Comment by hwshim0810** [comment]
I have confirmed that the auto&manual update is not working properly yesterday.
So I fixed that feature and will release updated apps tomorrow. 
and update version include feature that when widget click, show progress and load data. 
and auto update every hour.

I will add other features as well, so I hope you continue to use a lot.
Thanks for the comment.

**Comment by joshatron** [comment]
It looks like it is behaving correctly now. Thanks for fixing that and I can't wait to see what is next.
